version: '2.0'
services:
  app:
    build: bot
    container_name: weatherbot
    restart: always
    depends_on:
      - mongo
      - image-host
    env_file:
      env.env

  image-host:
    build: image-host
    volumes:
      - ./images:/data
    env_file:
      env.env
    restart: always

  mongo:
    image: mongo
    volumes:
      - ./data:/data
    restart: always