version: '2.0'
services:
  app:
    build: .
    container_name: weatherbot
    restart: always
    depends_on:
      - mongo
    env_file:
      env.env

  mongo:
    image: mongo
    volumes:
      - ./data:/data
    restart: always