version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    container_name: weatherbot
    restart: always
    depends_on:
    - redis
    env_file:
      env.env
    volumes:
      - ./:/usr/src/app

  redis:
    image: redis
    command: --appendonly yes
    volumes:
      - ./data:/data
    restart: always