version: '2.0'
services:
  bot:
    build:
      context: ./
      dockerfile: bot/Dockerfile-dev
    container_name: weatherbot
    restart: always
    depends_on:
    - mongo
    env_file:
      env.env
    volumes:
      - ./bot:/usr/src/app
    networks:
      - weatherbot
      - brightsky_api


  image-host:
    build:
      context: ./
      dockerfile: image-host/Dockerfile-dev
    volumes:
      - ./images:/data
      - ./image-host:/usr/src/app
    env_file:
      env.env
    restart: always
    networks:
      - weatherbot
      - system-proxy_default

  mongo:
    image: mongo
    volumes:
      - ./mongoData:/data
    restart: always
    networks:
      - weatherbot

networks:
  weatherbot:
    driver: bridge
  system-proxy_default:
    external: true
  brightsky_api:
    external: true