version: '2.0'
services:
  bot:
    build: bot
    container_name: weatherbot
    restart: always
    depends_on:
      - mongo
      - image-host
    env_file:
      env.env
    volumes:
      - ./cache:/cache
    networks:
      - weatherbot
      - brightsky_api
      # - system-proxy_default

  image-host:
    build: image-host
    container_name: weatherimages
    volumes:
      - ./images:/data
    env_file:
      env.env
    restart: always
    networks:
      - weatherbot
      - system-proxy_default

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    restart: always
    networks:
      - weatherbot


networks:
  weatherbot:
    driver: bridge
  system-proxy_default:
    external: true
  brightsky_api:
    external: true