FROM python:3.9.4-buster

WORKDIR /usr/src/app

RUN ls
RUN pwd
COPY ./requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./src/main.py" ]
# CMD [ "python", "./autoreload.py", "python", "./src/main.py" ]