version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: bot/Dockerfile-dev
    container_name: weatherbot
    restart: always
    depends_on:
    - mongo
    env_file:
      env.env
    volumes:
      - ./bot:/usr/src/app


  image-host:
    build:
      context: ./
      dockerfile: image-host/Dockerfile-dev
    volumes:
      - ./images:/data
      - ./image-host:/usr/src/app
    env_file:
      env.env
    ports:
      - 8000:80
    restart: always

  mongo:
    image: mongo
    volumes:
      - ./mongoData:/data
    restart: always