
version: '2.0'
services:
  app:
    build: ./dev-env
    depends_on:
    - mongo
    env_file:
      - token
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: nodemon dist/app.js

  build:
    build: ./dev-env
    volumes:
      - ./:/home/node/app
    command: npm run build-watch

  mongo:
    image: mongo:4.4.5-bionic
    volumes:
      - ./data:/data/db