FROM python:3.9.4-buster

WORKDIR /usr/src/app

RUN apt-get update \
  && apt-get install -y --no-install-recommends libcairo2-dev pkg-config \
  && rm -rf /var/lib/apt/lists/*

RUN ls
RUN pwd
COPY ./bot/requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

RUN python -m pip install -U py-mon colorama watchdog

CMD [ "pymon", "./main.py" ]